driver=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:3306/FDdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
username=root
password=2005
pool.minIdle=2
pool.maxPoolSize=10
pool.connectionTimeout=30000
pool.idleTimeout=600000
pool.maxLifetime=1800000